# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: offrecord-content

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-west-1

functions:
  content_post:
    handler: functions/content.post
    events:
      - http:
          method: post
          path: content
          request:
            schema:
              application/json: ${file(schemas/content_request.json)}

  content_discovery_get:
    handler: functions/content_discovery.get
    events:
      - http:
          method: get
          path: content/discovery/{user_id}
          request:
            parameters:
              paths:
                user_id: true

plugins:
  - serverless-offline
